name: Generate Snake Game

on:
  schedule:
    - cron: "0 */23 * * *" 
  workflow_dispatch:
  # push:
  #   branches:
  #   - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout to 'main' Branch âœ”ï¸
        uses: actions/checkout@v4.2.0

      - name: Generate SnakeGame.svg File ğŸ
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/assets/SnakeGame.svg
            profile/assets/SnakeGameDark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Setting up SSH key ğŸ”‘
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.JARVIS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Configure git with SSH key and author ğŸ› ï¸
        run: |
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/id_rsa
          git config --global commit.gpgsign true
          git config --global user.email "ritik.jarvis@gmail.com"
          git config --global user.name "itzzjarvis"

      - name: Sign Commit and Push Changes ğŸ‰
        run: |
          set +e
          git add .
          git commit -m "ğŸ SnakeGame Auto Generated"
          set -e
          git push